# Generated by Django 6.0.7 on 2026-09-29 16:41

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0027_profile_microsoft_id"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Quiz",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="測驗標題")),
                (
                    "pass_score",
                    models.PositiveSmallIntegerField(
                        default=60,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="及格分數",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="是否啟用"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
                (
                    "chapter",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quiz",
                        to="main.coursechapter",
                        verbose_name="章節",
                    ),
                ),
            ],
            options={
                "verbose_name": "章節測驗",
                "verbose_name_plural": "章節測驗",
            },
        ),
        migrations.CreateModel(
            name="QuizAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "score",
                    models.PositiveSmallIntegerField(default=0, verbose_name="分數"),
                ),
                (
                    "correct_count",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="答對題數"
                    ),
                ),
                (
                    "total_count",
                    models.PositiveSmallIntegerField(default=0, verbose_name="總題數"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作答時間"),
                ),
                (
                    "quiz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to="main.quiz",
                        verbose_name="測驗",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="使用者",
                    ),
                ),
            ],
            options={
                "verbose_name": "測驗作答紀錄",
                "verbose_name_plural": "測驗作答紀錄",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="QuizQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_text", models.TextField(verbose_name="題目")),
                ("options", models.JSONField(default=list, verbose_name="選項清單")),
                (
                    "correct_index",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="正確選項索引"
                    ),
                ),
                (
                    "explanation",
                    models.TextField(blank=True, default="", verbose_name="解析"),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=1, verbose_name="題目順序"),
                ),
                (
                    "quiz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="main.quiz",
                        verbose_name="測驗",
                    ),
                ),
            ],
            options={
                "verbose_name": "測驗題目",
                "verbose_name_plural": "測驗題目",
                "ordering": ["quiz", "sort_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="QuizAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "selected_index",
                    models.SmallIntegerField(default=-1, verbose_name="所選選項索引"),
                ),
                (
                    "is_correct",
                    models.BooleanField(default=False, verbose_name="是否答對"),
                ),
                (
                    "attempt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="main.quizattempt",
                        verbose_name="作答紀錄",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.quizquestion",
                        verbose_name="題目",
                    ),
                ),
            ],
            options={
                "verbose_name": "測驗答題明細",
                "verbose_name_plural": "測驗答題明細",
                "ordering": ["attempt", "question"],
            },
        ),
    ]
