# Generated by Django 6.0.5 on 2026-10-03 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_quiz_quizattempt_quizquestion_quizanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonprogress',
            name='page_open_count',
            field=models.PositiveIntegerField(default=0, verbose_name='單元頁開啟次數'),
        ),
        migrations.AddField(
            model_name='lessonprogress',
            name='replayed_seconds',
            field=models.PositiveIntegerField(default=0, verbose_name='重複觀看秒數'),
        ),
        migrations.AddField(
            model_name='lessonprogress',
            name='view_count',
            field=models.PositiveIntegerField(default=0, verbose_name='開啟觀看次數'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='quiz_type',
            field=models.CharField(choices=[('standard', '章節測驗'), ('remedial', 'AI 補救練習')], default='standard', max_length=20, verbose_name='測驗類型'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='source_attempt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='remedial_quizzes', to='main.quizattempt', verbose_name='弱點來源作答（僅 AI 補救練習使用）'),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='overall_feedback',
            field=models.TextField(blank=True, default='', verbose_name='AI 整體回饋'),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='strong_topics',
            field=models.JSONField(blank=True, default=list, verbose_name='AI 已掌握知識點'),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='weak_topics',
            field=models.JSONField(blank=True, default=list, help_text='[{"topic": str, "issue_description": str, "severity": "low|medium|high"}, ...]', verbose_name='AI 弱點知識點'),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='topic_tag',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='知識點標籤'),
        ),
        migrations.CreateModel(
            name='CourseSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField(blank=True, default='', verbose_name='摘要內容')),
                ('core_concepts', models.JSONField(blank=True, default=list, help_text='[{"concept": str, "explanation": str}, ...]', verbose_name='核心概念')),
                ('key_terms', models.JSONField(blank=True, default=list, help_text='[{"term": str, "definition": str}, ...]', verbose_name='關鍵名詞')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_summary', to='main.course', verbose_name='課程')),
            ],
            options={
                'verbose_name': 'AI 課程摘要',
                'verbose_name_plural': 'AI 課程摘要',
            },
        ),
    ]
